services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:5.8
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/neo4jAPI

